version: "3"
services:
  auth-db:
    image: postgres:11
    container_name: auth-db
    restart: always
    networks:
      - sgq-network
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=auth-db
    ports:
      - 5432:5432

  auth-api:
    build: "./auth"
    container_name: auth-api
    depends_on:
      - auth-db
    networks:
      - sgq-network
    environment:
      - PORT=3000
      - POSTGRES_HOST=auth-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=auth-db
    ports:
      - 3000:3000

  cip-db:
    image: postgres:11
    container_name: cip-db
    restart: always
    networks:
      - sgq-network
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=cip-db
      - POSTGRES_PORT=5433
    ports:
      - 5433:5432

  cip-api:
    build: "./cip"
    container_name: cip-api
    depends_on:
      - cip-db
    networks:
      - sgq-network
    environment:
      - PORT=3001
      - POSTGRES_HOST=cip-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=cip-db
    ports:
      - 3001:3001

  cpa-db:
    image: mongo
    container_name: cpa-db
    restart: always
    networks:
      - sgq-network
    environment:
      - MONGODB_USER=admin
      - MONGODB_DATABASE=cpa-db
      - MONGODB_PASSWORD=123456
    ports:
      - 27017:27017
      - 28017:28017

  cpa-api:
    build: "./cpa"
    container_name: cpa-api
    depends_on:
      - cpa-db
    networks:
      - sgq-network
    environment:
      - PORT=3002
      - MONGO_URL=mongodb://cpa-db:27017/cpa-db
    ports:
      - 3002:3002

  dt-api:
    build: "./dt"
    container_name: dt-api
    networks:
      - sgq-network
    environment:
      - PORT=3003
    ports:
      - 3003:3003

networks:
  sgq-network:
    driver: bridge
